repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: [--atomic, -m=3, -l=120, --tc]

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=120]
        language_version: python3.9
        additional_dependencies: ["click==8.0.4"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
        args:
          [
            --install-types,
            --non-interactive,
            --no-strict-optional,
            --ignore-missing-imports,
          ]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.7.4
    hooks:
      - id: pylint
        args:
          [
            --max-line-length=120,
            --disable=design,
            --disable=missing-docstring,
            --disable=bad-continuation,
            --disable=max-module-lines,
            --disable=useless-super-delegation,
            --disable=import-error,
            --disable=logging-fstring-interpolation,
            --disable=invalid-name,
            --disable=duplicate-code,
            --disable=len-as-condition,
            --disable=fixme,
            --disable=global-statement,
          ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace