pipeline {
    agent any
    environment {
        RUN_HEADLESS = 'True'
        HEADLESS = '-e RUN_HEADLESS=True'
    }

    stages {

    stage("Clone repository") {
        steps {
        checkout scm
    }
    }

    stage('Build image') {
        steps {
        sh "docker build -t web_test ."
    }
    }

    stage('Execute script') {
        steps {
        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
            sh "docker run \
                -e RUN_HEADLESS=True \
                --network='host' \
                --name example1 \
                --rm \
                --volume ${WORKSPACE}/allure-results/:/code/allure-results/ \
                --volume ${WORKSPACE}allure-results:/app/allure-results \
                --volume ${WORKSPACE}allure-reports:/app/default-reports \
                web_test \
                pytest tests/negative_tests/test_general_checks.py::TestGeneralChecks::test_check_wrong_title_of_the_page"
    }
    }
    }

    stage('Remove image') {
        steps {
        sh 'docker rmi web_test -f'
    }
    }

    stage('Allure Report') {
        steps {
            script {
            allure includeProperties: false, jdk: '', results: [[path: 'allure-results']]
    }
    }

}
}
}